language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - build-essential

script:
  - mkdir -p _build && cd _build || exit 1
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . -- -j$(nproc)
